# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

gaussian_elastic_arma <- function(y, x, lambdaVec, alpha, maxit, tol) {
    .Call('_elnglm_gaussian_elastic_arma', PACKAGE = 'elnglm', y, x, lambdaVec, alpha, maxit, tol)
}

binomial_elastic_arma <- function(y, x, lambdaVec, alpha, maxit, tol) {
    .Call('_elnglm_binomial_elastic_arma', PACKAGE = 'elnglm', y, x, lambdaVec, alpha, maxit, tol)
}

multinomial_elastic_arma <- function(y, x, lambdaVec, alpha, maxit, tol) {
    .Call('_elnglm_multinomial_elastic_arma', PACKAGE = 'elnglm', y, x, lambdaVec, alpha, maxit, tol)
}

